name: CI
on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      matrix:
        version:
          - '1.8'
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x86
          - x64
        exclude:
          # Remove some configurations from the build matrix to reduce CI time.
          # See https://github.com/marketplace/actions/setup-julia-environment
          # MacOS not available on x86
          - {os: 'macOS-latest', arch: 'x86'}
          # Don't test on all versions
          - {os: 'macOS-latest', version: '1.1'}
          - {os: 'macOS-latest', version: '1.2'}
          - {os: 'macOS-latest', version: '1.3'}
          - {os: 'windows-latest', version: '1.1'}
          - {os: 'windows-latest', version: '1.2'}
          - {os: 'windows-latest', version: '1.3'}
    steps:
      - uses: actions/checkout@v1
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
        env:
          ALPACA_KEY_ID: ${{ secrets.ALPACA_KEY_ID }}
          ALPACA_SECRET: ${{ secrets.ALPACA_SECRET }}
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    env:
      ALPACA_KEY_ID: ${{ secrets.ALPACA_KEY_ID }}
      ALPACA_SECRET: ${{ secrets.ALPACA_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using Trading
            DocMeta.setdocmeta!(Trading, :DocTestSetup, :(using Trading); recursive=true)
            doctest(Trading)'
